name: Cypress Tests frontend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "develop"
      - "main"
    paths:
      - frontend/src/**
      - frontend/cypress/**

jobs:
  install:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: admin
    name: E2E in Edge on windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@6c143abc292aa835d827652c2ea025d098311070
        with:
          working-directory: frontend
          install-command: yarn --frozen-lockfile --silent --network-timeout 1000000
          browser: edge
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
          spec: cypress/e2e/**/*.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_APP_NAME: Scenarios
          NEXT_PUBLIC_API_URL: http://localhost:3001
          NEXT_PUBLIC_API_PATH: /api
          NEXT_PUBLIC_INTRIC_API_URL: http://localhost:3002/api
          DOMAIN_NAME: localhost
          NEXT_PUBLIC_PROTECTED_ROUTES: ""
          HEALTH_AUTH: false
          HEALTH_USERNAME: ""
          HEALTH_PASSWORD: ""
          NEXT_PUBLIC_BACKGROUND_IMAGE: "/images/background.png"
          NEXT_PUBLIC_ASSISTANT_ID: test123
          NEXT_PUBLIC_ASSISTANT_APIKEY: testkey
